[package]
name = "get-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rfd = "0.11.3"
clap = { version = "4.2.7", features = ["derive"] }
